### ISSUE TITLE
qBittorent isn't working

### ISSUE THREAD

**Issue by jericjan** [Sparoney/RcloneLab#6]
When I click on "website", it just takes me to [this](https://i.imgur.com/iAShLvW.jpg). It also says it's successful but the page just doesn't load.

**Comment by Sparoney** [comment]
Hey, sorry but I haven't used this in months and haven't maintained it, but I believe the Backup Website or whatever the other option is for qBittorrent should work

**Comment by jericjan** [comment]
Thanks for the response. Unfortunately, none of them worked. But I did find this other notebook that used Ngrok instead of serveo:
https://github.com/sudo-ken/Torrents-to-Google-Drive

So all's good now.
